services:

  banco-reconpay:
    image: postgres:16
    container_name: reconpay-postgres
    environment:
      POSTGRES_DB: reconpay
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d reconpay" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - dados_reconpay:/var/lib/postgresql/data

  api-reconpay:
    build:
      context: .
      dockerfile: Dockerfile
    image: reconpay/api:1.0
    container_name: reconpay-api
    depends_on:
      banco-reconpay:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://banco-reconpay:5432/reconpay
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET:-BK4DqZtSaFy7ywhqiEK3TGdEZFfnbd0dBkAS9wxyIzM}

volumes:
  dados_reconpay:
