spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:dev-chave-local-apenas-para-desenvolvimento-min-32-chars}
  expiration: ${JWT_EXPIRATION:86400}

logging:
  level:
    org.hibernate.SQL: DEBUG
