package br.com.hanrry.reconpay.reconciliation.enums;

public enum DiscrepancyType {
    MISSING_SETTLEMENT,
    ORPHAN_SETTLEMENT,
    INCORRECT_AMOUNT,
    FEE_DIVERGENCE,
    STATUS_MISMATCH,
    PAYMENT_METHOD_MISMATCH,
    INSTALLMENTS_MISMATCH,
    BANK_AMOUNT_MISMATCH,
    MISSING_BANK_CREDIT,
    ORPHAN_BANK_CREDIT,
    AMBIGUOUS_BANK_MATCH
}
