UPDATE users SET role = 'FINANCIAL_ANALYST' WHERE role = 'USER';

ALTER TABLE users DROP CONSTRAINT users_role_check;

ALTER TABLE users ALTER COLUMN role SET DEFAULT 'FINANCIAL_ANALYST';

ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'FINANCIAL_ANALYST'));
